name: Swift-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init SPM
      swift package init --type library
    - name: Swift Package Gen Project
      swift package generate-xcodeproj
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
